name: converterpro
description: Unit and currencies converter

version: 2.6.0+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Needed to store the customizations and the latest currencies convertions
  shared_preferences: ^2.0.5
  #Needed to open external pages such as GitHub repo, Play Store, etc
  url_launcher: ^6.0.3
  #Needed to download the latest currencies convertions
  http: ^0.13.1
  #Needed to improve the state management
  provider: ^5.0.0
  #Needed for translation
  intl: ^0.17.0
  #Needed for speed dial on large screen
  flutter_speed_dial:
    git:
      url: https://github.com/ferraridamiano/flutter_speed_dial
  #Needed for unit conversion
  units_converter: ^0.3.0+1
    #git:
    #  url: https://github.com/ferraridamiano/units_converter
    #path: ../units_converter

  flutter_localizations:
      sdk: flutter

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
        - resources/images/
