name: converterpro
description: Unit and currencies converter

version: 2.3.2+21

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Needed to store the customizations and the latest currencies convertions
  shared_preferences: ^0.5.8
  #Needed to open external pages such as GitHub repo, Play Store, etc
  url_launcher: ^5.5.0
  #Needed to download the latest currencies convertions
  http: ^0.12.2

  flutter_localizations:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
        - resources/images/
        - resources/lang/
