name: exchange_rates
description: Exchange rates api from ECB
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Needed for downloading exchange rates from internet
  http: ^1.1.0
  # Needed for DateFormat
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.2
  test: ^1.16.0
